name: Kaspi ETL Snapshot

on:
  schedule:
    # Ежедневно в 06:00 Asia/Almaty (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Almaty
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run Kaspi ETL
        run: |
          python etl/run_etl.py --config etl/config.yaml

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaspi-market-snapshot
          path: |
            data/latest/market_snapshot.csv
            data/daily/*.csv

      - name: Commit updated CSV (optional)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "etl-bot"
          git config user.email "etl-bot@example.com"
          git add data/latest/market_snapshot.csv data/daily/*.csv || true
          git commit -m "ETL: update market snapshot" || echo "no changes"
          git push

